### ISSUE TITLE
請求支持o1-mini和o1-preview模型

### ISSUE THREAD

**Issue by dennis-kipnis** [Yanyutin753/RefreshToV1Api#11]
OpenAI上了新模型，請求更新追加支持，感謝！

**Comment by Yanyutin753** [comment]
更新了试试呗

**Comment by dennis-kipnis** [comment]
> 更新了试试呗

謝謝大佬

**Comment by dennis-kipnis** [comment]
> 更新了试试呗

報錯了，大佬，日志提示 ori_model_name 這個變量有問題
2024-09-13 19:58:20,559 [INFO] - New Request
2024-09-13 19:58:20,564 [ERROR] - Exception on /v1/chat/completions [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/main.py", line 1881, in chat_completions
    if "o1-" in ori_model_name:
UnboundLocalError: local variable 'ori_model_name' referenced before assignment
2024-09-13 19:58:20,572 [INFO] - 107.172.5.133 - - [13/Sep/2024 19:58:20] "POST /v1/chat/completions HTTP/1.1" 500 -

**Comment by dennis-kipnis** [comment]
報錯了，大佬，日志提示 ori_model_name 這個變量有問題
2024-09-13 19:58:20,559 [INFO] - New Request
2024-09-13 19:58:20,564 [ERROR] - Exception on /v1/chat/completions [POST]
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 194, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
File "/app/main.py", line 1881, in chat_completions
if "o1-" in ori_model_name:
UnboundLocalError: local variable 'ori_model_name' referenced before assignment
2024-09-13 19:58:20,572 [INFO] - {domain} - - [13/Sep/2024 19:58:20] "POST /v1/chat/completions HTTP/1.1" 500 -

**Comment by Yanyutin753** [comment]
2分钟之后试试

**Comment by dennis-kipnis** [comment]
> 2分钟之后试试

現在已經可以了！就是o1系列的流式輸出和preview的消息處理好像還存在一些小問題，期待後續優化❀！

**Comment by Yanyutin753** [comment]
有什么问题 给出报错

**Comment by Yanyutin753** [comment]
错误是什么 没看懂

**Comment by SailFlorve** [comment]
好像会吃掉前几个token

**Comment by Yanyutin753** [comment]
更新之后再举例子

**Comment by wzhanjun** [comment]
大佬麻烦更新下镜像，用的docker镜像，好像不是最新的

**Comment by wzhanjun** [comment]
最后一次提交的代码缩进好像有问题， 多了一个空格

**Comment by Yanyutin753** [comment]
来pr 现在没环境 都是手机改的😭😭😭

**Comment by Yanyutin753** [comment]
手机改 有点bug

**Comment by Yanyutin753** [comment]
应该好了

**Comment by wzhanjun** [comment]
嗯，可以了，刚fork，拉下最新代码，发现大佬已经改好了，哈哈，辛苦大佬
